apiVersion: v1
kind: Service
metadata:
  name: demo-app-1
  namespace: demo-app1-prod
spec:
  ports:
    - name: application
      port: 8080
      targetPort: 8080
    - name: exporter
      port: 8081
      targetPort: 8081
  selector:
    app: demo-app-1
  type: ClusterIP
