# Build stage
# FROM maven:3.9-eclipse-temurin-21 AS builder
FROM image-registry.openshift-image-registry.svc:5000/tooling/openliberty-jdk21-rdm:24.0.0.9-java21 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
# FROM eclipse-temurin:21-jre
FROM image-registry.openshift-image-registry.svc:5000/tooling/openliberty-jdk21-rdm:24.0.0.9-java21
WORKDIR /app
COPY --from=builder /app/target/monitor-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
